import Head from 'next/head';
import styles from '../styles/Home.module.css';
import ActivityList from '../components/activities/activity-list';
import { getFeaturedActivities } from '../dummy-activities-data';

export default function Home() {
  const featuredActivities = getFeaturedActivities();
  console.log(featuredActivities);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">ShopFlow</a>
        </h1>
        <p>This is the Dashboard Page.</p>
      </div>
      <h2>Featured Activities</h2>
      <ActivityList activities={featuredActivities} />
    </div>
  );
}
